config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
  	resources :likes
  end
  
  devise_for :users, controllers: {
  	registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'tweets/new', to:'tweets#create'
  root to: 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
   validates :content, presence: true
   has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		tweets_path
	end 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :find_post
	before_action :find_like, only: [:destroy]

def create
  if already_liked?
    flash[:notice] = "You can't like more than once"
  else
    @tweet.likes.create(user_id: current_user.id)
  end
  redirect_to tweets_path
end

def destroy
  if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    @like.destroy
  end
  redirect_to tweets_path
end	

  private
  def find_post
    @tweet = Tweet.find(params[:tweet_id])
  end

  def already_liked?
  Like.where(user_id: current_user.id, tweet_id:
  params[:tweet_id]).exists?
  end

  def find_like
   @like = @tweet.likes.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:show, :index]
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    if user_signed_in?
        @tweets = Tweet.paginate(:page => params[:page], :per_page => 50)
    end

  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

   respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: 'se ha creado' }
        
      else
        format.html { redirect_to tweets_path, notice: 'ha ocurrido un error' }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.permit(:content)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/homes/index.html.erb
<div class="container-fluid">
        
  <div class="row">
           
   <div class="col-6 slider color display-5">
                   
      <p class="my-5 "><i class="fas fa-search"></i><span class="ima">Sigue lo que te interesa.</span></p>
  	  <p class="my-5"><i class="fas fa-user-friends"></i><span class="ima">Entérate de qué está hablando la gente.</span></p>
      <p class="my-5"><i class="far fa-comment"></i><span class="ima">Únete a la conversación.</span></p>    
                     
     </div>

 <div class="col-6 texto">
      
     <i class="fab fa-twitter"></i>              
     <p class="p">Mira lo que esta pasando en el mundo en este momento</p>
     <p class="p1">Unete a Twitter hoy mismo</p>
     <button type="button"class="btn btn-outline-primary"><%= link_to "iniciar sesion", new_user_session_path %></button> <br><br>
	  <button type="button"class="btn btn-outline-primary"><%= link_to "registrarse", new_user_registration_path %></button>
     </div> 
    </div> 
   </div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
     <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e7cd580bf0.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editar </h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
  <nav class=" na navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><i class="fab fa-twitter"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>
      </ul>
      
       <div class="text field d-flex justify-content-end">
        <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete%>
      </div>
     
    </div>
  </nav>







  <div class="container">
    <div class="">
       <%= form_with(url:'/tweets/new', local: true, class:'form-group d-flex justify-content-center') do |form| %>
       </div>
     <div class="w-50 ">

      <%= form.text_area :content, cols:40, rows:4, placeholder:'¿que estas pensando?',  class:'form-control' %>

    </div>

   
    <div class="">
      <%= form.submit :tweet, class:'btn btn-primary' %>
    </div>
    <p id="notice" class="title">Bienvenido</p>
  <% end %>

    
   

      <% @tweets.order(created_at: :desc).each do |tweet| %>
      <div class="card my-5  mx-0">

    <div class="dropdown ml-auto">
    <button class=" colorb btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      
    </button>
    <div class="dropdown-menu " aria-labelledby="dropdownMenuButton">
      <% if current_user == tweet.user %>
    <%= link_to 'Show', tweet, class:'dropdown-item' %>
    <%= link_to 'Edit', edit_tweet_path(tweet), class:'dropdown-item' %>
    <%= link_to 'Destroy', tweet, class:'dropdown-item', method: :delete, data: { confirm: 'Are you sure?' } %>
     <% else %>
          <%= link_to 'Show', tweet, class:'dropdown-item'%>
      <% end %>
        <% pre_like = tweet.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
             <span><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%></span><%= button_to 'Unlike', tweet_like_path(tweet, pre_like), method: :delete %>
        <% else %>
            <span><%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%></span><%= button_to 'Like', tweet_likes_path(tweet), method: :post %>
        <% end %>
    </div>
  </div>
    
    <div class="imgredonda">
      <img src="<%= tweet.user.image%>" width="50px" heigth="50px" alt="">
       <%= tweet.user.name %> <br>
      <span class="content"><%= tweet.content %></span>
      <span class="content "><%=link_to  time_ago_in_words(tweet.created_at), tweet %></span>
     
    </div>
    
  </div>

  <% end %>
  <%= will_paginate @tweets %>
  </div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @tweet.user.name %>
</p>

<p>
  <strong>contenido:</strong>
  <%= @tweet.content %>
</p>

<div class="imgredonda">
	<strong>imagen:</strong>
	<img src="<%= @tweet.user.image%>" width="50px" heigth="50px" alt="">
</div>
	
	<br>
	<br>
	<div>
		<p class="seg">followers:</p><%=@tweet.likes.count%><p class="seg">seguidores</p>
		<%@tweet.likes.each do |like| %>
		<span class="imgredonda"><%= image_tag like.user.image, width:"4%" %></span>
		<% end %>
	</div>
<br>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>